Integration of M-Elo
MEITREX/quiz_service pull request #1
Opened 2024-06-18 08:58 UTC by Nimeggis

## Checklist for reviewer

- The code is easy to understand
- The code follows
  the [coding guidelines](https://github.com/MEITREX/wiki/blob/main/dev-manuals/backend/coding-guidelines.md) of
  this project
- The code is tested or if not, the reason is documented or discussed
- The added and existing tests reasonably cover the code change
- The code has no breaking changes in the database schema or if so, the assignee is aware of it and
  will perform a database migration

2024-06-20 08:06 UTC, PaulBredl submitted a review, later dismissed
Wie schon in Discord geschrieben, einmal formatting durchlaufen lassen wäre nciht schlecht

2024-06-27 00:35 UTC, myluki2000 requested changes
See my longer comments in the gateway PR

2024-06-27 00:35 UTC, myluki2000 commented on src/main/resources/graphql/service/mutation.graphqls
> +    itemId: UUID
This should most likely not require passing an ID.

2024-06-27 00:35 UTC, myluki2000 commented on src/main/resources/graphql/service/mutation.graphqls
> +    itemId:UUID
This should most likely not  require passing an ID.

2024-06-27 00:35 UTC, myluki2000 commented on src/main/resources/graphql/service/mutation.graphqls
> +    itemId:UUID
This should most likely not require passing an ID.

2024-07-08 14:45 UTC, myluki2000 approved these changes

2024-08-01 11:25 UTC, myluki2000 approved these changes

2024-08-01 12:57 UTC, merged